cassandra.contactpoints=127.0.0.1
cassandra.port=9142
cassandra.keyspace=testKeySpace

#spring.cassandra.keyspace-name=testKeySpace
#spring.cassandra.contact-points=127.0.0.1
#spring.cassandra.port=9142
#spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
